### ISSUE TITLE
Regarding custom database 

### ISSUE THREAD

**Issue by sahilrishav2** [wshuai294/PStrain#15]
Hi @wshuai294 ,

I want to know if i could build a custom database for the latest release of pstrain that supports MetaPhlan4. As for the pre customized database, the tool is not performing well with it. So, I am thinking of reanalysing with a custom database. If i could build a custom database with the latest release then kindly guide. 

Thank you in advance.

**Comment by wshuai294** [comment]
Hello, I don't know which database do you mean. If you mean the Metaphlan4 marker gene database, you can use map reads to your own database, and profile strain for each species separately using `scripts/single_species.py`. If you mean the `prior database`, currently it does not support using prior database with Metaphlan4 yet. Maybe adjusting parameters like `-w` and `--elbow` will help.

**Comment by sahilrishav2** [comment]
Ok, thank you. I mean to say I wanted to make a custom database for
specific species but as you said currently it doesn't support prior
database then i will continue with the results that i currently obtained
through PStrain.

Thanking You
Rishav Sahil

**Comment by wshuai294** [comment]
Ok. Pls let me know if you have any queries.

**Comment by sahilrishav2** [comment]
No, I have just completed the benchmarking of tools and in the process of
writing the manuscript. Thank you once again for all your support and
patience in this entire process.

With regards
Rishav Sahil

**Comment by wshuai294** [comment]
It's my pleasure. Good luck with your paper!
