### ISSUE TITLE
How to make a marker gene?

### ISSUE THREAD

**Issue by zckoo007** [wshuai294/PStrain#3]
Hi Shuai

I have a new genome, but I don't know how to make genome to marker gene. Can you give me some idea?

Bests
Chengkai

**Comment by wshuai294** [comment]
Hi Chengkai,

I think there are three possible solutions. First, you could map the new genome to the metaphlan database, and check if there is a hit. Maybe the new genome's marker gene is already in the database. Second, you could use PStrain's single species mode, you can use Bwa to map your reads to the genome, and call SNP by yourself. Then you can run PStrain with the bam and vcf file. You can find the single species mode tutorial in the readme file.  However, the homologous regions from other species may affect the results.  Finally, you can follow the metaphlan's method to build your own marker gene database. However, it would cost a lot of effort.

Please let me know if it helps.

Sincerely,
WANG Shuai
