### ISSUE TITLE
The strain_RA.txt different from the intermediate metaphlan2_output.txt

### ISSUE THREAD

**Issue by weiting-liang** [wshuai294/PStrain#5]
Hi shuai!
I found that strain_RA.txt different from the intermediate metaphlan2_output.txt.
The strain_RA results contradicted my simulated data while the metaphlan2_output.txt showed the correct abundance, so I checked the metaphlan2_output.txt and strain_RA result by comparing their species's abundance. The abundance of the species is different between strain_RA.txt and metaphlan2_output.txt.

# strain_RA.txt
# Species | Species_RA
Bifidobacterium_bifidum | 36.7256
Bacteroides_thetaiotaomicron | 13.17946
Odoribacter_splanchnicus | 10.54507
Odoribacter_splanchnicus | 10.54507
Odoribacter_splanchnicus | 10.54507
Prevotella_intermedia | 9.94046
Prevotella_intermedia | 9.94046
Prevotella_intermedia | 9.94046
Alistipes_finegoldii | 7.29353
Clostridium_butyricum | 4.98109
Clostridium_butyricum | 4.98109
Clostridium_butyricum | 4.98109
Clostridium_sporogenes | 3.69829
Clostridium_sporogenes | 3.69829
Clostridium_sporogenes | 3.69829
Clostridium_pasteurianum | 2.43552
Clostridium_pasteurianum | 2.43552
Clostridium_tetani | 1.57689
Clostridium_stercorarium | 1.5142
Clostridium_stercorarium | 1.5142
Clostridium_stercorarium | 1.5142
Clostridium_stercorarium | 1.5142
Megasphaera_elsdenii | 1.27493
Bordetella_bronchiseptica_parapertussis | 0.68471
Bordetella_bronchiseptica_parapertussis | 0.68471
Bordetella_bronchiseptica_parapertussis | 0.68471
Bordetella_holmesii | 0.61797
Bordetella_pertussis | 0.58863
Bordetella_pertussis | 0.58863
Bordetella_pertussis | 0.58863
Bordetella_petrii | 0.55972
Bordetella_petrii | 0.55972
Taylorella_equigenitalis | 0.50617
Desulfovibrio_africanus | 0.40631
Desulfovibrio_vulgaris | 0.34669
Desulfovibrio_vulgaris | 0.34669
Desulfovibrio_vulgaris | 0.34669
Desulfovibrio_vulgaris | 0.34669
Haemophilus_influenzae | 0.33584
Achromobacter_xylosoxidans | 0.40631
Haemophilus_ducreyi | 0.29188
Coraliomargarita_akajimensis | 10.54507
Roseburia_hominis | 9.94046
Clostridium_botulinum | 2.43552
Clostridium_saccharobutylicum | 0.50617
Desulfitobacterium_dichloroeliminans | 0.32522

# metaphlan2_output.txt
s__Bordetella_pertussis |   | 36.7256
s__Bordetella_petrii |   | 13.17946
s__Coraliomargarita_akajimensis |   | 10.54507
s__Roseburia_hominis |   | 9.94046
s__Clostridium_stercorarium |   | 7.29353
s__Clostridium_butyricum |   | 4.98109
s__Bordetella_bronchiseptica_parapertussis | 3.69829
s__Clostridium_botulinum |   | 2.43552
s__Clostridium_pasteurianum |   | 1.57689
s__Prevotella_intermedia |   | 1.5142
s__Desulfovibrio_vulgaris |   | 1.27493
s__Odoribacter_splanchnicus |   | 0.68471
s__Bordetella_holmesii |   | 0.61797
s__Bifidobacterium_bifidum |   | 0.58863
s__Clostridium_sporogenes |   | 0.55972
s__Clostridium_saccharobutylicum | 0.50617
s__Achromobacter_xylosoxidans |   | 0.40631
s__Bacteroides_thetaiotaomicron |   | 0.34669
s__Candidatus_Arthromitus_unclassified | 0.33744
s__Taylorella_equigenitalis |   | 0.33584
s__Desulfovibrio_africanus |   | 0.32804
s__Desulfitobacterium_dichloroeliminans | 0.32522
s__Alistipes_finegoldii |   | 0.31922
s__Haemophilus_ducreyi |   | 0.29188
s__Haemophilus_influenzae |   | 0.27104
s__Clostridium_tetani |   | 0.26774
s__Achromobacter_unclassified |   | 0.21043
s__Megasphaera_unclassified |   | 0.13154
s__Megasphaera_elsdenii |   | 0.1292
s__Pusillimonas_unclassified |   | 0.07615
s__Butyrivibrio_unclassified |   | 0.06459
s__Coriobacterium_glomerans |   | 0.03642

I'm not sure if I'm running it wrong. Here is my run command and log.
$ cat run.sh
python /ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting2/software/PStrain/install/scripts/PStrain.py -c config.txt -o ./output -p 4 -n 8 --dbdir /ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting2/software/PStrain/install/db --prior /ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting2/software/PStrain/install/db/prior_beta.pickle --bowtie2-build /ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting2/software/PStrain/install/packages/bowtie2-2.3.1-legacy/bowtie2-build --bowtie2 /ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting2/software/PStrain/install/packages/bowtie2-2.3.1-legacy/bowtie2 --samtools /ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting2/software/PStrain/install/packages/SamTools-1.3.1/samtools --metaphlan2 /ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting2/software/PStrain/install/packages/metaphlan2/metaphlan2.py --gatk /ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting2/software/PStrain/install/packages/GATK_3.5/GenomeAnalysisTK.jar --picard /ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting2/software/PStrain/install/packages/picard-tools-2.1.0/picard.jar

log is too big to show, so I attach it here.
[log.txt](https://github.com/wshuai294/PStrain/files/6168472/log.txt)

Best,
Liang

**Comment by wshuai294** [comment]
Hi Liang,

I checked the strain_RA.txt and metaphlan2_output.txt that you sent, and I found no difference between the two files.  Could you tell me in which species you found the difference?   

For Pstrain's output, the second column represents the species' relative abundance, while the fifth column represents strain's relative abundance.  So the values of the second column for the strains that belong to the same species are the same.

Thank you.

Best,
WANG Shuai

**Comment by weiting-liang** [comment]
Hi shuai! 

For example, in strain_RA.txt, the dominant species is Bifidobacterium_bifidum with the 36.7256 abundance, but in the metaphlan2_output.txt, the dominant species is Bordetella_pertussis also with the 36.7256 abundance. I think it maybe something wrong written in strain_RA.txt.


Sincerely
Liang

**Comment by wshuai294** [comment]
Hi Liang,

Thank you for your careful check. There is a bug giving the species RA value in the whole sample. I have fixed it in the pipeline.py. Please test if it is correct now.

Thanks,
WANG Shuai

**Comment by weiting-liang** [comment]
Hi shuai!

Thanks for your correction, now the programs work well. 

Best,
Liang
