### ISSUE TITLE
Java version for GATK?

### ISSUE THREAD

**Issue by yuxiangtan** [wshuai294/PStrain#7]
I got the following the error, which should be at the GATK step:

[Sun May 23 22:52:52 CST 2021] picard.sam.AddOrReplaceReadGroups done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2155872256
##### ERROR ------------------------------------------------------------------------------------------

I googled and someone said it is because of the Java version, so what't the java version should be?

Best,

Yuxiang

**Comment by yuxiangtan** [comment]
I install the GATK3.8 from conda in which the java version works for the GATK3.5 provided by the author.

**Comment by wshuai294** [comment]
That's Great.  

The java version I used is 
```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
```
