### ISSUE TITLE
A snippet offering a for-loop based config construction script

### ISSUE THREAD

**Issue by ctseto** [wshuai294/PStrain#8]
With input fastq in a root directory, in individual folders for each sample, and runs named $sample\_1.fastq and $sample\_2.fastq, and the names are assigned to a variable, $AllSamples

for I in $AllSamples; do echo "//";echo sample : $I ; echo fq1: /rootdir/$I/$I\_1.fastq ; echo fq2: /rootdir/$I/$I\_2.fastq ; done

**Comment by wshuai294** [comment]
Thank you for your useful script.
